name: http_asset_service
description: A service for managing assets from a server.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  test_storage:
    git:
      url: https://github.com/gnarhard/test_storage.git
      ref: main
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  path_provider: ^2.0.12
dependencies:
  http: ^0.13.5
  flutter_archive: ^5.0.0
  rxdart: ^0.27.7
  flutter:
    sdk: flutter
