name: http_asset_service
description: A service for managing assets from a server.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
dependencies:
  http: ^0.13.5
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  flutter_archive: ^5.0.0
